### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by jerrywalters** [jerrywalters/platform-health#1]
## Description
Determine which metrics to show, which charts to use for those metrics, and the corresponding design and styles for those charts

### Todo List
- [ ] decide on metrics
- [ ] decide on which charts to use for which metric
- [ ] chart design
- [ ] add charts and structure the data for the charts
- [ ] chart styles and customization
