### ISSUE TITLE
API Health

### ISSUE THREAD

**Issue by jerrywalters** [jerrywalters/platform-health#2]
## Description
Create a page to display similar information but specific to a single API

### Todo List
- [ ] copy everything over from platform health page
- [ ] determine if there are metrics specific to individual API
- [ ] change markup to reflect API specific information
