### ISSUE TITLE
Favorited APIs

### ISSUE THREAD

**Issue by jerrywalters** [jerrywalters/platform-health#3]
## Description
Finish design and styles "favorite API" items (80% there)

### Todo List
- [ ] Favorite APIs - "are they stupid and do I care?"
- [ ] Favorited item design
- [ ] Favorited item style tweaks

**Comment by jerrywalters** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oC6Km7ct&#x2F;15-favorite-apis"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Favorite APIs</a>

**Comment by jerrywalters** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xKHaM11Y&#x2F;16-api-health"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> API Health</a>
