### ISSUE TITLE
Sticky status header

### ISSUE THREAD

**Issue by jerrywalters** [jerrywalters/platform-health#4]
## Description
Make a sticky status bar for the header on scroll

### Todo List
- [ ] sticky header design
- [ ] sticky header styles
- [ ] sticky header make it sticky

**Comment by jerrywalters** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;iZSPmg8z&#x2F;9-sticky-status-header"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Sticky Status Header</a>
